database: database_name # will be suffixed with "_<env>", e.g. "_development"

hoptoad:
  token: 1234

pivotal_tracker:
  token: 1234
  projects:
    - 123
    - 456

github:
  login: someone
  token: 1234

highrise:
  token: 1234
  
log_level: WARN

feeds:
   - http://one.com/feed/atom
   - http://two.com/feed/atom
   
twitter:
 user: jason
 list: haters